name: giglert
description: "Premium Android notification alarm app for Fiverr freelancers."
publish_to: 'none'

version: 1.0.1+10

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  google_sign_in: ^7.2.0
  provider: ^6.1.5+1
  flutter_local_notifications: ^21.0.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.5
  audioplayers: ^6.6.0
  google_fonts: ^8.1.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"
  remove_alpha_ios: true



  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/logo_with_des.png

