// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    final FirebaseOptions? options = currentPlatformOrNull;
    if (options != null) {
      return options;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions? get currentPlatformOrNull {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return null;
      default:
        return null;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD2A167HbrS6neyfBhAXxvR54tlfvdw4g',
    appId: '1:429377546777:web:1fbea9da0aa399b387d888',
    messagingSenderId: '429377546777',
    projectId: 'giglert',
    authDomain: 'giglert.firebaseapp.com',
    storageBucket: 'giglert.firebasestorage.app',
    measurementId: 'G-KQNM4HVHHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD0JpQl9bcb0HYtNlLmTWKd68exEm1eyM',
    appId: '1:429377546777:android:fb8abbafaeb0987587d888',
    messagingSenderId: '429377546777',
    projectId: 'giglert',
    storageBucket: 'giglert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTgyq4QyXXLD90sG83YobqUSgBYW8noMs',
    appId: '1:429377546777:ios:95f15411c43b54d387d888',
    messagingSenderId: '429377546777',
    projectId: 'giglert',
    storageBucket: 'giglert.firebasestorage.app',
    iosBundleId: 'com.example.notifier',
  );
}
